# Generated by Django 3.2 on 2021-04-28 10:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Article_title', models.CharField(max_length=255, verbose_name='Название статьи')),
                ('Article_text', models.TextField(verbose_name='Текст статьи')),
                ('Article_publication', models.DateTimeField(default=datetime.datetime(2021, 4, 28, 13, 43, 3, 563997), verbose_name='Дата и время публикации')),
            ],
            options={
                'verbose_name': 'Article (verbose, single)',
                'verbose_name_plural': 'Articles (verbose, plural)',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment_author', models.CharField(max_length=255, verbose_name='Автор комментария')),
                ('Comment_text', models.CharField(max_length=500, verbose_name='Текст комментария')),
                ('Comment_Article_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.article')),
            ],
            options={
                'verbose_name': 'Comment (verbose, single)',
                'verbose_name_plural': 'Comments (verbose, plural)',
            },
        ),
    ]
