# Generated by Django 3.2 on 2021-04-28 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Article_publication',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 28, 13, 48, 19, 535170), verbose_name='Дата и время публикации'),
        ),
    ]
