# Generated by Django 3.2 on 2021-04-28 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_article_article_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Article_publication',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 28, 14, 22, 12, 933460), verbose_name='Дата и время публикации'),
        ),
    ]
