# Generated by Django 3.2 on 2021-04-28 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_article_article_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Article_publication',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 28, 19, 43, 58, 756765), verbose_name='Дата и время публикации'),
        ),
    ]
