# Generated by Django 3.2 on 2021-04-28 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_article_article_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Article_publication',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 0, 32, 51, 920422), verbose_name='Дата и время публикации'),
        ),
    ]
