# Generated by Django 3.2 on 2021-04-29 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_article_article_publication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Article_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Article_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Comment_Article_FK',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Comment_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Comment_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='article',
            name='Article_publication',
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 9, 38, 4, 723964), verbose_name='Дата и время публикации'),
        ),
    ]
